function calculer(){
    age=document.getElementsByName("age")
    sport=document.getElementsByName("abb")
    c=document.getElementById("ah").value
    for(i=0;i<age.length;i++){
        if(age[i].checked){
            a=i
        }
    }
    for(i=0;i<age.length;i++){
        if(sport[i].checked){
            b=i
        }
    }
    
    c=document.getElementById("ah").value
    if(age[a].value=="E"){
        if(sport[b]=="1"){
            if(c=="G"){
                document.getElementById("ou").innerHTML="40"
            }
            else{
                document.getElementById("ou").innerHTML="30"
            }
        }
        else{
            if(c=="G"){
                document.getElementById("ou").innerHTML="100"
            }
            else{
                document.getElementById("ou").innerHTML="80"
            }
        }
    }
    else{
         if(sport[b]=="1"){
            if(c=="G"){
                document.getElementById("ou").innerHTML="50"
            }
            else{
                document.getElementById("ou").innerHTML="40"
            }
        }
        else{
            if(c=="G"){
                document.getElementById("ou").innerHTML="140"
            }
            else{
                document.getElementById("ou").innerHTML="100"
            }
        }
    }
}
